In [75]:
import pandas as pd
import torch

In [76]:
character_map_file = 'Data/Character-Maps/Characters-Tamil.txt'
char_map_df = pd.read_csv(character_map_file)
print(char_map_df.shape)

(247, 3)


In [77]:
char_map_df

Character Consonant Glyph
0           அ         -     -
1           ஆ         -     ா
2           இ         -     ி
3           ஈ         -     ீ
4           உ         -     ு
..        ...       ...   ...
242        னை         ன     ை
243        னொ         ன     ொ
244        னோ         ன     ோ
245        னௌ         ன     ௌ
246         ஃ         ஃ     -

[247 rows x 3 columns]

In [78]:
characters = set()
for character in char_map_df['Character'].values:
    characters.update(list(character))
characters = sorted(list(characters))

In [79]:
characters

['ஃ',
 'அ',
 'ஆ',
 'இ',
 'ஈ',
 'உ',
 'ஊ',
 'எ',
 'ஏ',
 'ஐ',
 'ஒ',
 'ஓ',
 'ஔ',
 'க',
 'ங',
 'ச',
 'ஞ',
 'ட',
 'ண',
 'த',
 'ந',
 'ன',
 'ப',
 'ம',
 'ய',
 'ர',
 'ற',
 'ல',
 'ள',
 'ழ',
 'வ',
 'ா',
 'ி',
 'ீ',
 'ு',
 'ூ',
 'ெ',
 'ே',
 'ை',
 'ொ',
 'ோ',
 'ௌ',
 '்']

In [80]:
list("அறிவித்தது")

['அ', 'ற', 'ி', 'வ', 'ி', 'த', '்', 'த', 'த', 'ு']

In [81]:
glyphs = char_map_df['Glyph'].unique()
print(glyphs)

['-' 'ா' 'ி' 'ீ' 'ு' 'ூ' 'ெ' 'ே' 'ை' 'ொ' 'ோ' 'ௌ' '்']


In [82]:
strings = ["அறிவித்தது", "புதுச்சேரி", "ஆவடி "]
for str_ in strings:
    unicode_tokens = list(str_)
    print(unicode_tokens)
    original_tokens = []
    for unicode_token in unicode_tokens:
        if unicode_token in glyphs:
            original_tokens[-1] += unicode_token
        else:
            original_tokens.append(unicode_token)
    print(original_tokens)

['அ', 'ற', 'ி', 'வ', 'ி', 'த', '்', 'த', 'த', 'ு']
['அ', 'றி', 'வி', 'த்', 'த', 'து']
['ப', 'ு', 'த', 'ு', 'ச', '்', 'ச', 'ே', 'ர', 'ி']
['பு', 'து', 'ச்', 'சே', 'ரி']
['ஆ', 'வ', 'ட', 'ி', ' ']
['ஆ', 'வ', 'டி', ' ']


In [83]:
char_map_df = char_map_df.set_index(['Consonant', 'Glyph']).unstack()['Character'].fillna('*')

In [84]:
char_map_df

Glyph      -   ா   ி   ீ   ு   ூ   ெ   ே   ை   ொ   ோ   ௌ   ்
Consonant                                                   
-          அ   ஆ   இ   ஈ   உ   ஊ   எ   ஏ   ஐ   ஒ   ஓ   ஔ   *
ஃ          ஃ   *   *   *   *   *   *   *   *   *   *   *   *
க          க  கா  கி  கீ  கு  கூ  கெ  கே  கை  கொ  கோ  கௌ  க்
ங          ங  ஙா  ஙி  ஙீ  ஙு  ஙூ  ஙெ  ஙே  ஙை  ஙொ  ஙோ  ஙௌ  ங்
ச          ச  சா  சி  சீ  சு  சூ  செ  சே  சை  சொ  சோ  சௌ  ச்
ஞ          ஞ  ஞா  ஞி  ஞீ  ஞு  ஞூ  ஞெ  ஞே  ஞை  ஞொ  ஞோ  ஞௌ  ஞ்
ட          ட  டா  டி  டீ  டு  டூ  டெ  டே  டை  டொ  டோ  டௌ  ட்
ண          ண  ணா  ணி  ணீ  ணு  ணூ  ணெ  ணே  ணை  ணொ  ணோ  ணௌ  ண்
த          த  தா  தி  தீ  து  தூ  தெ  தே  தை  தொ  தோ  தௌ  த்
ந          ந  நா  நி  நீ  நு  நூ  நெ  நே  நை  நொ  நோ  நௌ  ந்
ன          ன  னா  னி  னீ  னு  னூ  னெ  னே  னை  னொ  னோ  னௌ  ன்
ப          ப  பா  பி  பீ  பு  பூ  பெ  பே  பை  பொ  போ  பௌ  ப்
ம          ம  மா  மி  மீ  மு  மூ  மெ  மே  மை  மொ  மோ  மௌ  ம்
ய          ய  யா  யி  யீ  யு  யூ  யெ  யே  யை  யொ  யோ  யௌ  ய்
ர          ர  ரா  ரி  ரீ  ரு  ரூ  ரெ  ரே  ரை  ரொ  ரோ  ரௌ  ர்
ற          ற  றா  றி  றீ  று  றூ  றெ  றே  றை  றொ  றோ  றௌ  ற்
ல          ல  லா  லி  லீ  லு  லூ  லெ  லே  லை  லொ  லோ  லௌ  ல்
ள          ள  ளா  ளி  ளீ  ளு  ளூ  ளெ  ளே  ளை  ளொ  ளோ  ளௌ  ள்
ழ          ழ  ழா  ழி  ழீ  ழு  ழூ  ழெ  ழே  ழை  ழொ  ழோ  ழௌ  ழ்
வ          வ  வா  வி  வீ  வு  வூ  வெ  வே  வை  வொ  வோ  வௌ  வ்

In [97]:
list('ஆலா')

['ஆ', 'ல', 'ா']

In [95]:


char_split

{'அ': {'consonant': '-', 'glyph': '-'},
 'ஆ': {'consonant': '-', 'glyph': 'ா'},
 'இ': {'consonant': '-', 'glyph': 'ி'},
 'ஈ': {'consonant': '-', 'glyph': 'ீ'},
 'உ': {'consonant': '-', 'glyph': 'ு'},
 'ஊ': {'consonant': '-', 'glyph': 'ூ'},
 'எ': {'consonant': '-', 'glyph': 'ெ'},
 'ஏ': {'consonant': '-', 'glyph': 'ே'},
 'ஐ': {'consonant': '-', 'glyph': 'ை'},
 'ஒ': {'consonant': '-', 'glyph': 'ொ'},
 'ஓ': {'consonant': '-', 'glyph': 'ோ'},
 'ஔ': {'consonant': '-', 'glyph': 'ௌ'},
 '*': {'consonant': 'ஃ', 'glyph': '்'},
 'ஃ': {'consonant': 'ஃ', 'glyph': '-'},
 'க': {'consonant': 'க', 'glyph': '-'},
 'கா': {'consonant': 'க', 'glyph': 'ா'},
 'கி': {'consonant': 'க', 'glyph': 'ி'},
 'கீ': {'consonant': 'க', 'glyph': 'ீ'},
 'கு': {'consonant': 'க', 'glyph': 'ு'},
 'கூ': {'consonant': 'க', 'glyph': 'ூ'},
 'கெ': {'consonant': 'க', 'glyph': 'ெ'},
 'கே': {'consonant': 'க', 'glyph': 'ே'},
 'கை': {'consonant': 'க', 'glyph': 'ை'},
 'கொ': {'consonant': 'க', 'glyph': 'ொ'},
 'கோ': {'consonant': 'க', 'glyp

In [38]:
char_map_df.values.flatten().tolist()

['அ',
 'ஆ',
 'இ',
 'ஈ',
 'உ',
 'ஊ',
 'எ',
 'ஏ',
 'ஐ',
 'ஒ',
 'ஓ',
 'ஔ',
 '*',
 'ஃ',
 '*',
 '*',
 '*',
 '*',
 '*',
 '*',
 '*',
 '*',
 '*',
 '*',
 '*',
 '*',
 'க',
 'கா',
 'கி',
 'கீ',
 'கு',
 'கூ',
 'கெ',
 'கே',
 'கை',
 'கொ',
 'கோ',
 'கௌ',
 'க்',
 'ங',
 'ஙா',
 'ஙி',
 'ஙீ',
 'ஙு',
 'ஙூ',
 'ஙெ',
 'ஙே',
 'ஙை',
 'ஙொ',
 'ஙோ',
 'ஙௌ',
 'ங்',
 'ச',
 'சா',
 'சி',
 'சீ',
 'சு',
 'சூ',
 'செ',
 'சே',
 'சை',
 'சொ',
 'சோ',
 'சௌ',
 'ச்',
 'ஞ',
 'ஞா',
 'ஞி',
 'ஞீ',
 'ஞு',
 'ஞூ',
 'ஞெ',
 'ஞே',
 'ஞை',
 'ஞொ',
 'ஞோ',
 'ஞௌ',
 'ஞ்',
 'ட',
 'டா',
 'டி',
 'டீ',
 'டு',
 'டூ',
 'டெ',
 'டே',
 'டை',
 'டொ',
 'டோ',
 'டௌ',
 'ட்',
 'ண',
 'ணா',
 'ணி',
 'ணீ',
 'ணு',
 'ணூ',
 'ணெ',
 'ணே',
 'ணை',
 'ணொ',
 'ணோ',
 'ணௌ',
 'ண்',
 'த',
 'தா',
 'தி',
 'தீ',
 'து',
 'தூ',
 'தெ',
 'தே',
 'தை',
 'தொ',
 'தோ',
 'தௌ',
 'த்',
 'ந',
 'நா',
 'நி',
 'நீ',
 'நு',
 'நூ',
 'நெ',
 'நே',
 'நை',
 'நொ',
 'நோ',
 'நௌ',
 'ந்',
 'ன',
 'னா',
 'னி',
 'னீ',
 'னு',
 'னூ',
 'னெ',
 'னே',
 'னை',
 'னொ',
 'னோ',
 'னௌ',
 'ன்',
 'ப',
 'பா',
 'பி',
 'பீ',
 'பு',


In [54]:
batch_size = 8
time_steps = 3
num_consonants = 5
num_glyphs = 2

c = torch.arange(batch_size*time_steps*num_consonants).view((batch_size, time_steps, num_consonants))
g = torch.arange(batch_size*time_steps*num_glyphs).view((batch_size, time_steps, -1))

print(c.shape)
print(c)
print()
print(g.shape)
print(g)

torch.Size([8, 3, 5])
tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14]],

        [[ 15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29]],

        [[ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44]],

        [[ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74]],

        [[ 75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89]],

        [[ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104]],

        [[105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]])

torch.Size([8, 3, 2])
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7

In [55]:
c1 = c.view(-1, num_consonants, 1)
g1 = g.view(-1, 1, num_glyphs)

print(c1.shape)
print(c1)
print()
print(g1.shape)
print(g1)

torch.Size([24, 5, 1])
tensor([[[  0],
         [  1],
         [  2],
         [  3],
         [  4]],

        [[  5],
         [  6],
         [  7],
         [  8],
         [  9]],

        [[ 10],
         [ 11],
         [ 12],
         [ 13],
         [ 14]],

        [[ 15],
         [ 16],
         [ 17],
         [ 18],
         [ 19]],

        [[ 20],
         [ 21],
         [ 22],
         [ 23],
         [ 24]],

        [[ 25],
         [ 26],
         [ 27],
         [ 28],
         [ 29]],

        [[ 30],
         [ 31],
         [ 32],
         [ 33],
         [ 34]],

        [[ 35],
         [ 36],
         [ 37],
         [ 38],
         [ 39]],

        [[ 40],
         [ 41],
         [ 42],
         [ 43],
         [ 44]],

        [[ 45],
         [ 46],
         [ 47],
         [ 48],
         [ 49]],

        [[ 50],
         [ 51],
         [ 52],
         [ 53],
         [ 54]],

        [[ 55],
         [ 56],
         [ 57],
         [ 58],
         [ 

In [58]:
(c1*g1)

tensor([[[   0,    0],
         [   0,    1],
         [   0,    2],
         [   0,    3],
         [   0,    4]],

        [[  10,   15],
         [  12,   18],
         [  14,   21],
         [  16,   24],
         [  18,   27]],

        [[  40,   50],
         [  44,   55],
         [  48,   60],
         [  52,   65],
         [  56,   70]],

        [[  90,  105],
         [  96,  112],
         [ 102,  119],
         [ 108,  126],
         [ 114,  133]],

        [[ 160,  180],
         [ 168,  189],
         [ 176,  198],
         [ 184,  207],
         [ 192,  216]],

        [[ 250,  275],
         [ 260,  286],
         [ 270,  297],
         [ 280,  308],
         [ 290,  319]],

        [[ 360,  390],
         [ 372,  403],
         [ 384,  416],
         [ 396,  429],
         [ 408,  442]],

        [[ 490,  525],
         [ 504,  540],
         [ 518,  555],
         [ 532,  570],
         [ 546,  585]],

        [[ 640,  680],
         [ 656,  697],
         [ 672,  7

In [57]:
char1 = c1*g1
print(char1.shape)

torch.Size([24, 5, 2])


In [60]:
char1.view(batch_size, time_steps, num_consonants, num_glyphs)[7]

tensor([[[4410, 4515],
         [4452, 4558],
         [4494, 4601],
         [4536, 4644],
         [4578, 4687]],

        [[4840, 4950],
         [4884, 4995],
         [4928, 5040],
         [4972, 5085],
         [5016, 5130]],

        [[5290, 5405],
         [5336, 5452],
         [5382, 5499],
         [5428, 5546],
         [5474, 5593]]])